# Problem Statement

* About Dataset: The purpose of this dataset is to help us understand customer behavior and purchasing data in a supermarket mall through membership cards. The data includes basic information about customers such as their ID, age, gender, annual income, and spending score. Spending score is a parameter assigned to customers based on their purchasing behavior. The goal of this dataset is to use unsupervised ML techniques to segment the customers into groups and identify the target customers who are likely to converge. By understanding the customers better, the mall can plan their marketing strategy accordingly and increase their revenue. This dataset is designed for learning purposes and serves as an excellent example of how to use unsupervised machine learning algorithms in practice.
* Problem Statement and Objective The mall wants to understand the customer segments to better target marketing efforts and improve sales. The objective of this project is to identify distinct customer segments and provide recommendations to the marketing team to develop targeted marketing strategies.

# Assignment:

### Part1: Modeling, Hyperparameter Tuning & Evaluation
- Modeling for customer segmentation (use pycaret to experiment with multiple algorithms )
- Select one of the best performing algorithms based on clustering model evaluation metrics. (Good to plot the datapoints in 3d and evaluate as well.
- Improve the performance of the shortlisted model
- Compare the evaluation metrics for the optimal combination of parameters.

### Part2: Model Explanation & Understanding
- Do the prediction on the training dataset for assigning clusters/labels to each row.
- Approach1 (Manual Analysis): Do the cluster/segment analysis
    - See the average mean of feature values for different clusters
    - Analyze it and try to give them the meaningful name (rather than cluster_0, cluster_1, we want to assign them a meaningful self explanatory name)
        - For example:
            - if Mean Age is 25, and Mean Income is 57k in cluster 1 , then the name can be "Young Moderate Income"
            - if Mean Age is 27 and Mean Income is 25k in cluster 2, then the name can be "Young Low Income"
- Approach2 (Using classification algorithm for model explaination): Train a classification model using the labelled data, that means you have to use the cluster labels as your Target variable now.
    - Once the classification model is trained, do the Global & Local explaination using SHAP & LIME libraries.
    - Put your observation for this
    - Think in terms of if the clustering labels are meaningful or not.
- Compare your understanding and observations from both the approaches and see if they are inline.
    - Goal here is to re-validate the model and establish a trust.

- Finalize model: Train the selected algorithm over the entire dataset (TRAIN + TEST) using the optimal hyperparameter values.
- Export the model file in the pickle format and save it in a "./model" directory. (use proper naming and version)

NOTE: Dataset is small and simple, Focus should be on trying out different techniques and get your hands dirty.

# Write-up
* Explain in detail your observations, outcomes and why you have taken a certain approach over the other. Keep the code modular and efficient.

In [3]:
from pathlib import Path

ROOT_DIR = Path().resolve()
ROOT_DIR

DATA_DIR = ROOT_DIR / "mall_customers.csv"

In [4]:
import pandas as pd 
import numpy as np

In [7]:
customer_data = pd.read_csv(DATA_DIR)
df = customer_data.copy(deep=True)
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [10]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000